"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.categoriesRoutes = void 0;
const express_1 = require("express");
const categories_controller_1 = require("../controllers/categories_controller");
const authorization_1 = require("../middleware/authorization");
exports.categoriesRoutes = (0, express_1.Router)();
exports.categoriesRoutes.get('/categories', authorization_1.authenticateToken, categories_controller_1.getCategories);
exports.categoriesRoutes.get('/categories/:id', authorization_1.authenticateToken, categories_controller_1.getCategoriesById);
exports.categoriesRoutes.post('/createCategories', authorization_1.authenticateToken, categories_controller_1.createCategories);
exports.categoriesRoutes.delete('/deleteCategories/:id', authorization_1.authenticateToken, categories_controller_1.deleteCategories);
exports.categoriesRoutes.put('/updateCategories/:id', authorization_1.authenticateToken, categories_controller_1.updateCategories);
